version: "2"
services:
  varnish:
    image: eeacms/varnish
    ports:
    - "80:6081"
    - "6085:6085"
    environment:
      COOKIES: "true"
      COOKIES_WHITELIST: "(SESS[a-z0-9]+|SSESS[a-z0-9]+|NO_CACHE)"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "3s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
      DASHBOARD_USER: "admin"
      DASHBOARD_PASSWORD: "admin"
      DASHBOARD_SERVERS: "varnish"
      DASHBOARD_DNS_ENABLED: "true"